import {createAction} from 'redux-actions'

export const LOGIN_PHONE_ACCOUNT = 'LOGIN_PHONE_ACCOUNT'
const LOGIN_PHONE_ACCOUNT_REQUEST = 'LOGIN_PHONE_ACCOUNT_REQUEST'
const LOGIN_PHONE_ACCOUNT_SUCCESS = 'LOGIN_PHONE_ACCOUNT_SUCCESS'
const LOGIN_PHONE_ACCOUNT_ERROR = 'LOGIN_PHONE_ACCOUNT_ERROR'

export const LOGOUT_PHONE_ACCOUNT = 'LOGOUT_PHONE_ACCOUNT'
const LOGOUT_PHONE_ACCOUNT_REQUEST = 'LOGOUT_PHONE_ACCOUNT_REQUEST'
const LOGOUT_PHONE_ACCOUNT_SUCCESS = 'LOGOUT_PHONE_ACCOUNT_SUCCESS'
const LOGOUT_PHONE_ACCOUNT_ERROR = 'LOGOUT_PHONE_ACCOUNT_ERROR'

export const LOGIN_FACEBOOK_ACCOUNT = 'LOGIN_FACEBOOK_ACCOUNT'
const LOGIN_FACEBOOK_ACCOUNT_REQUEST = 'LOGIN_FACEBOOK_ACCOUNT_REQUEST'
const LOGIN_FACEBOOK_ACCOUNT_SUCCESS = 'LOGIN_FACEBOOK_ACCOUNT_SUCCESS'
const LOGIN_FACEBOOK_ACCOUNT_ERROR = 'LOGIN_FACEBOOK_ACCOUNT_ERROR'

export const LOGOUT_FACEBOOK_ACCOUNT = 'LOGOUT_FACEBOOK_ACCOUNT'
const LOGOUT_FACEBOOK_ACCOUNT_REQUEST = 'LOGOUT_FACEBOOK_ACCOUNT_REQUEST'
const LOGOUT_FACEBOOK_ACCOUNT_SUCCESS = 'LOGOUT_FACEBOOK_ACCOUNT_SUCCESS'
const LOGOUT_FACEBOOK_ACCOUNT_ERROR = 'LOGOUT_FACEBOOK_ACCOUNT_ERROR'

export const LOGIN_GOOGLE_ACCOUNT = 'LOGIN_GOOGLE_ACCOUNT'
const LOGIN_GOOGLE_ACCOUNT_REQUEST = 'LOGIN_GOOGLE_ACCOUNT_REQUEST'
const LOGIN_GOOGLE_ACCOUNT_SUCCESS = 'LOGIN_GOOGLE_ACCOUNT_SUCCESS'
const LOGIN_GOOGLE_ACCOUNT_ERROR = 'LOGIN_GOOGLE_ACCOUNT_ERROR'

export const LOGOUT_GOOGLE_ACCOUNT = 'LOGOUT_GOOGLE_ACCOUNT'
const LOGOUT_GOOGLE_ACCOUNT_REQUEST = 'LOGOUT_GOOGLE_ACCOUNT_REQUEST'
const LOGOUT_GOOGLE_ACCOUNT_SUCCESS = 'LOGOUT_GOOGLE_ACCOUNT_SUCCESS'
const LOGOUT_GOOGLE_ACCOUNT_ERROR = 'LOGOUT_GOOGLE_ACCOUNT_ERROR'

export const LOGIN_EMPLOYEE_ACCOUNT = 'LOGIN_EMPLOYEE_ACCOUNT'
const LOGIN_EMPLOYEE_ACCOUNT_REQUEST = 'LOGIN_EMPLOYEE_ACCOUNT_REQUEST'
const LOGIN_EMPLOYEE_ACCOUNT_SUCCESS = 'LOGIN_EMPLOYEE_ACCOUNT_SUCCESS'
const LOGIN_EMPLOYEE_ACCOUNT_ERROR = 'LOGIN_EMPLOYEE_ACCOUNT_ERROR'

export const LOGOUT_EMPLOYEE_ACCOUNT = 'LOGOUT_EMPLOYEE_ACCOUNT'
const LOGOUT_EMPLOYEE_ACCOUNT_REQUEST = 'LOGOUT_EMPLOYEE_ACCOUNT_REQUEST'
const LOGOUT_EMPLOYEE_ACCOUNT_SUCCESS = 'LOGOUT_EMPLOYEE_ACCOUNT_SUCCESS'
const LOGOUT_EMPLOYEE_ACCOUNT_ERROR = 'LOGOUT_EMPLOYEE_ACCOUNT_ERROR'

export const loginPhoneAccountRequest = createAction(LOGIN_PHONE_ACCOUNT_REQUEST)
export const loginPhoneAccountSuccess = createAction(LOGIN_PHONE_ACCOUNT_SUCCESS)
export const loginPhoneAccountError = createAction(LOGIN_PHONE_ACCOUNT_ERROR)

export const logoutPhoneAccountRequest = createAction(LOGOUT_PHONE_ACCOUNT_REQUEST)
export const logoutPhoneAccountSuccess = createAction(LOGOUT_PHONE_ACCOUNT_SUCCESS)
export const logoutPhoneAccountError = createAction(LOGOUT_PHONE_ACCOUNT_ERROR)

export const loginFacebookAccountRequest = createAction(LOGIN_FACEBOOK_ACCOUNT_REQUEST)
export const loginFacebookAccountSuccess = createAction(LOGIN_FACEBOOK_ACCOUNT_SUCCESS)
export const loginFacebookAccountError = createAction(LOGIN_FACEBOOK_ACCOUNT_ERROR)

export const logoutFacebookAccountRequest = createAction(LOGOUT_FACEBOOK_ACCOUNT_REQUEST)
export const logoutFacebookAccountSuccess = createAction(LOGOUT_FACEBOOK_ACCOUNT_SUCCESS)
export const logoutFacebookAccountError = createAction(LOGOUT_FACEBOOK_ACCOUNT_ERROR)

export const loginGoogleAccountRequest = createAction(LOGIN_GOOGLE_ACCOUNT_REQUEST)
export const loginGoogleAccountSuccess = createAction(LOGIN_GOOGLE_ACCOUNT_SUCCESS)
export const loginGoogleAccountError = createAction(LOGIN_GOOGLE_ACCOUNT_ERROR)

export const logoutGoogleAccountRequest = createAction(LOGOUT_GOOGLE_ACCOUNT_REQUEST)
export const logoutGoogleAccountSuccess = createAction(LOGOUT_GOOGLE_ACCOUNT_SUCCESS)
export const logoutGoogleAccountError = createAction(LOGOUT_GOOGLE_ACCOUNT_ERROR)

export const loginEmployeeAccountRequest = createAction(LOGIN_EMPLOYEE_ACCOUNT_REQUEST)
export const loginEmployeeAccountSuccess = createAction(LOGIN_EMPLOYEE_ACCOUNT_SUCCESS)
export const loginEmployeeAccountError = createAction(LOGIN_EMPLOYEE_ACCOUNT_ERROR)

export const logoutEmployeeAccountRequest = createAction(LOGOUT_EMPLOYEE_ACCOUNT_REQUEST)
export const logoutEmployeeAccountSuccess = createAction(LOGOUT_EMPLOYEE_ACCOUNT_SUCCESS)
export const logoutEmployeeAccountError = createAction(LOGOUT_EMPLOYEE_ACCOUNT_ERROR)
