import {createAction} from 'redux-actions'

export const ADD_DEVICE = 'ADD_DEVICE'
const ADD_DEVICE_REQUEST = 'ADD_DEVICE_REQUEST'
const ADD_DEVICE_SUCCESS = 'ADD_DEVICE_SUCCESS'
const ADD_DEVICE_ERROR = 'ADD_DEVICE_ERROR'

export const FETCH_DEVICE = 'FETCH_DEVICE'
const FETCH_DEVICE_REQUEST = 'FETCH_DEVICE_REQUEST'
const FETCH_DEVICE_SUCCESS = 'FETCH_DEVICE_SUCCESS'
const FETCH_DEVICE_ERROR = 'FETCH_DEVICE_ERROR'

export const SEND_MESSENGER = 'SEND_MESSENGER'
const SEND_MESSENGER_REQUEST = 'SEND_MESSENGER_REQUEST'
const SEND_MESSENGER_SUCCESS = 'SEND_MESSENGER_SUCCESS'
const SEND_MESSENGER_ERROR = 'SEND_MESSENGER_ERROR'

export const SEND_ABSENTFORM = 'SEND_ABSENTFORM'
const SEND_ABSENTFORM_REQUEST = 'SEND_ABSENTFORM_REQUEST'
const SEND_ABSENTFORM_SUCCESS = 'SEND_ABSENTFORM_SUCCESS'
const SEND_ABSENTFORM_ERROR = 'SEND_ABSENTFORM_ERROR'

export const UPDATE_ABSENTFORM = 'UPDATE_ABSENTFORM'
const UPDATE_ABSENTFORM_REQUEST = 'UPDATE_ABSENTFORM_REQUEST'
const UPDATE_ABSENTFORM_SUCCESS = 'UPDATE_ABSENTFORM_SUCCESS'
const UPDATE_ABSENTFORM_ERROR = 'UPDATE_ABSENTFORM_ERROR'

export const GET_MESSENGER_MANAGER = 'GET_MESSENGER_MANAGER'
const GET_MESSENGER_MANAGER_REQUEST = 'GET_MESSENGER_MANAGER_REQUEST'
const GET_MESSENGER_MANAGER_SUCCESS = 'GET_MESSENGER_MANAGER_SUCCESS'
const GET_MESSENGER_MANAGER_ERROR = 'GET_MESSENGER_MANAGER_ERROR'

export const DELETE_MESSENGER_MANAGER = 'DELETE_MESSENGER_MANAGER'
const DELETE_MESSENGER_MANAGER_REQUEST = 'DELETE_MESSENGER_MANAGER_REQUEST'
const DELETE_MESSENGER_MANAGER_SUCCESS = 'DELETE_MESSENGER_MANAGER_SUCCESS'
const DELETE_MESSENGER_MANAGER_ERROR = 'DELETE_MESSENGER_MANAGER_ERROR'

export const GET_MESSENGER_EMPLOYEE = 'GET_MESSENGER_EMPLOYEE'
const GET_MESSENGER_EMPLOYEE_REQUEST = 'GET_MESSENGER_EMPLOYEE_REQUEST'
const GET_MESSENGER_EMPLOYEE_SUCCESS = 'GET_MESSENGER_EMPLOYEE_SUCCESS'
const GET_MESSENGER_EMPLOYEE_ERROR = 'GET_MESSENGER_EMPLOYEE_ERROR'

export const DELETE_MESSENGER_EMPLOYEE = 'DELETE_MESSENGER_EMPLOYEE'
const DELETE_MESSENGER_EMPLOYEE_REQUEST = 'DELETE_MESSENGER_EMPLOYEE_REQUEST'
const DELETE_MESSENGER_EMPLOYEE_SUCCESS = 'DELETE_MESSENGER_EMPLOYEE_SUCCESS'
const DELETE_MESSENGER_EMPLOYEE_ERROR = 'DELETE_MESSENGER_EMPLOYEE_ERROR'

export const GET_ABSENTFORM_MANAGER = 'GET_ABSENTFORM_MANAGER'
const GET_ABSENTFORM_MANAGER_REQUEST = 'GET_ABSENTFORM_MANAGER_REQUEST'
const GET_ABSENTFORM_MANAGER_SUCCESS = 'GET_ABSENTFORM_MANAGER_SUCCESS'
const GET_ABSENTFORM_MANAGER_ERROR = 'GET_ABSENTFORM_MANAGER_ERROR'

export const GET_ABSENTFORM_EMPLOYEE = 'GET_ABSENTFORM_EMPLOYEE'
const GET_ABSENTFORM_EMPLOYEE_REQUEST = 'GET_ABSENTFORM_EMPLOYEE_REQUEST'
const GET_ABSENTFORM_EMPLOYEE_SUCCESS = 'GET_ABSENTFORM_EMPLOYEE_SUCCESS'
const GET_ABSENTFORM_EMPLOYEE_ERROR = 'GET_ABSENTFORM_EMPLOYEE_ERROR'

export const ACCEPT_ABSENTFORM_EMPLOYEE = 'ACCEPT_ABSENTFORM_EMPLOYEE'
const ACCEPT_ABSENTFORM_EMPLOYEE_REQUEST = 'ACCEPT_ABSENTFORM_EMPLOYEE_REQUEST'
const ACCEPT_ABSENTFORM_EMPLOYEE_SUCCESS = 'ACCEPT_ABSENTFORM_EMPLOYEE_SUCCESS'
const ACCEPT_ABSENTFORM_EMPLOYEE_ERROR = 'ACCEPT_ABSENTFORM_EMPLOYEE_ERROR'

export const REMOVE_ABSENTFORM_EMPLOYEE = 'REMOVE_ABSENTFORM_EMPLOYEE'
const REMOVE_ABSENTFORM_EMPLOYEE_REQUEST = 'REMOVE_ABSENTFORM_EMPLOYEE_REQUEST'
const REMOVE_ABSENTFORM_EMPLOYEE_SUCCESS = 'REMOVE_ABSENTFORM_EMPLOYEE_SUCCESS'
const REMOVE_ABSENTFORM_EMPLOYEE_ERROR = 'REMOVE_ABSENTFORM_EMPLOYEE_ERROR'

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION'
const PUSH_NOTIFICATION_REQUEST = 'PUSH_NOTIFICATION_REQUEST'
const PUSH_NOTIFICATION_SUCCESS = 'PUSH_NOTIFICATION_SUCCESS'
const PUSH_NOTIFICATION_ERROR = 'PUSH_NOTIFICATION_ERROR'

export const addDeviceRequest = createAction(ADD_DEVICE_REQUEST)
export const addDeviceSuccess = createAction(ADD_DEVICE_SUCCESS)
export const addDeviceError = createAction(ADD_DEVICE_ERROR)

export const fetchDeviceRequest = createAction(FETCH_DEVICE_REQUEST)
export const fetchDeviceSuccess = createAction(FETCH_DEVICE_SUCCESS)
export const fetchDeviceError = createAction(FETCH_DEVICE_ERROR)

export const sendMessengerRequest = createAction(SEND_MESSENGER_REQUEST)
export const sendMessengerSuccess = createAction(SEND_MESSENGER_SUCCESS)
export const sendMessengerError = createAction(SEND_MESSENGER_ERROR)

export const sendAbsentformRequest = createAction(SEND_ABSENTFORM_REQUEST)
export const sendAbsentformSuccess = createAction(SEND_ABSENTFORM_SUCCESS)
export const sendAbsentformError = createAction(SEND_ABSENTFORM_ERROR)

export const updateAbsentformRequest = createAction(UPDATE_ABSENTFORM_REQUEST)
export const updateAbsentformSuccess = createAction(UPDATE_ABSENTFORM_SUCCESS)
export const updateAbsentformError = createAction(UPDATE_ABSENTFORM_ERROR)

export const getMessengerManagerRequest = createAction(GET_MESSENGER_MANAGER_REQUEST)
export const getMessengerManagerSuccess = createAction(GET_MESSENGER_MANAGER_SUCCESS)
export const getMessengerManagerError = createAction(GET_MESSENGER_MANAGER_ERROR)

export const deleteMessengerManagerRequest = createAction(DELETE_MESSENGER_MANAGER_REQUEST)
export const deleteMessengerManagerSuccess = createAction(DELETE_MESSENGER_MANAGER_SUCCESS)
export const deleteMessengerManagerError = createAction(DELETE_MESSENGER_MANAGER_ERROR)

export const getMessengerEmployeeRequest = createAction(GET_MESSENGER_EMPLOYEE_REQUEST)
export const getMessengerEmployeeSuccess = createAction(GET_MESSENGER_EMPLOYEE_SUCCESS)
export const getMessengerEmployeeError = createAction(GET_MESSENGER_EMPLOYEE_ERROR)

export const deleteMessengerEmployeeRequest = createAction(DELETE_MESSENGER_EMPLOYEE_REQUEST)
export const deleteMessengerEmployeeSuccess = createAction(DELETE_MESSENGER_EMPLOYEE_SUCCESS)
export const deleteMessengerEmployeeError = createAction(DELETE_MESSENGER_EMPLOYEE_ERROR)

export const getAbsentformManagerRequest = createAction(GET_ABSENTFORM_MANAGER_REQUEST)
export const getAbsentformManagerSuccess = createAction(GET_ABSENTFORM_MANAGER_SUCCESS)
export const getAbsentformManagerError = createAction(GET_ABSENTFORM_MANAGER_ERROR)

export const getAbsentformEmployeeRequest = createAction(GET_ABSENTFORM_EMPLOYEE_REQUEST)
export const getAbsentformEmployeeSuccess = createAction(GET_ABSENTFORM_EMPLOYEE_SUCCESS)
export const getAbsentformEmployeeError = createAction(GET_ABSENTFORM_EMPLOYEE_ERROR)

export const acceptAbsentformEmployeeRequest = createAction(ACCEPT_ABSENTFORM_EMPLOYEE_REQUEST)
export const acceptAbsentformEmployeeSuccess = createAction(ACCEPT_ABSENTFORM_EMPLOYEE_SUCCESS)
export const acceptAbsentformEmployeeError = createAction(ACCEPT_ABSENTFORM_EMPLOYEE_ERROR)

export const removeAbsentformEmployeeRequest = createAction(REMOVE_ABSENTFORM_EMPLOYEE_REQUEST)
export const removeAbsentformEmployeeSuccess = createAction(REMOVE_ABSENTFORM_EMPLOYEE_SUCCESS)
export const removeAbsentformEmployeeError = createAction(REMOVE_ABSENTFORM_EMPLOYEE_ERROR)

export const pushNotificationRequest = createAction(PUSH_NOTIFICATION_REQUEST)
export const pushNotificationSuccess = createAction(PUSH_NOTIFICATION_SUCCESS)
export const pushNotificationError = createAction(PUSH_NOTIFICATION_ERROR)

const ADD_RECEIVED_MESSENGER_EMPLOYEE = 'ADD_RECEIVED_MESSENGER_EMPLOYEE'
export const addReceivedMessengerEmployee = createAction(ADD_RECEIVED_MESSENGER_EMPLOYEE)

const REMOVE_RECEIVED_MESSENGER_EMPLOYEE = 'REMOVE_RECEIVED_MESSENGER_EMPLOYEE'
export const removeReceivedMessengerEmployee = createAction(REMOVE_RECEIVED_MESSENGER_EMPLOYEE)

const ADD_ALL_RECEIVED_MESSENGER_EMPLOYEE = 'ADD_ALL_RECEIVED_MESSENGER_EMPLOYEE'
export const addAllReceivedMessengerEmployee = createAction(ADD_ALL_RECEIVED_MESSENGER_EMPLOYEE)
