import {createAction} from 'redux-actions'

export const UPDATE_SERVICE_CHILD = 'UPDATE_SERVICE_CHILD'
const UPDATE_SERVICE_CHILD_REQUEST = 'UPDATE_SERVICE_CHILD_REQUEST'
const UPDATE_SERVICE_CHILD_SUCCESS = 'UPDATE_SERVICE_CHILD_SUCCESS'
const UPDATE_SERVICE_CHILD_ERROR = 'UPDATE_SERVICE_CHILD_ERROR'

export const DELETE_SERVICE_CHILD = 'DELETE_SERVICE_CHILD'
const DELETE_SERVICE_CHILD_REQUEST = 'DELETE_SERVICE_CHILD_REQUEST'
const DELETE_SERVICE_CHILD_SUCCESS = 'DELETE_SERVICE_CHILD_SUCCESS'
const DELETE_SERVICE_CHILD_ERROR = 'DELETE_SERVICE_CHILD_ERROR'

export const FETCH_MODEL_SERVICE_CHILD = 'FETCH_MODEL_SERVICE_CHILD'
const FETCH_MODEL_SERVICE_CHILD_REQUEST = 'FETCH_MODEL_SERVICE_CHILD_REQUEST'
const FETCH_MODEL_SERVICE_CHILD_SUCCESS = 'FETCH_MODEL_SERVICE_CHILD_SUCCESS'
const FETCH_MODEL_SERVICE_CHILD_ERROR = 'FETCH_MODEL_SERVICE_CHILD_ERROR'

export const FETCH_OPTION_SERVICE_CHILD = 'FETCH_OPTION_SERVICE_CHILD'
const FETCH_OPTION_SERVICE_CHILD_REQUEST = 'FETCH_OPTION_SERVICE_CHILD_REQUEST'
const FETCH_OPTION_SERVICE_CHILD_SUCCESS = 'FETCH_OPTION_SERVICE_CHILD_SUCCESS'
const FETCH_OPTION_SERVICE_CHILD_ERROR = 'FETCH_OPTION_SERVICE_CHILD_ERROR'

export const updateServiceChildRequest = createAction(UPDATE_SERVICE_CHILD_REQUEST)
export const updateServiceChildSuccess = createAction(UPDATE_SERVICE_CHILD_SUCCESS)
export const updateServiceChildError = createAction(UPDATE_SERVICE_CHILD_ERROR)

export const deleteServiceChildRequest = createAction(DELETE_SERVICE_CHILD_REQUEST)
export const deleteServiceChildSuccess = createAction(DELETE_SERVICE_CHILD_SUCCESS)
export const deleteServiceChildError = createAction(DELETE_SERVICE_CHILD_ERROR)

export const fetchModelServiceChildRequest = createAction(FETCH_MODEL_SERVICE_CHILD_REQUEST)
export const fetchModelServiceChildSuccess = createAction(FETCH_MODEL_SERVICE_CHILD_SUCCESS)
export const fetchModelServiceChildError = createAction(FETCH_MODEL_SERVICE_CHILD_ERROR)

export const fetchOptionServiceChildRequest = createAction(FETCH_OPTION_SERVICE_CHILD_REQUEST)
export const fetchOptionServiceChildSuccess = createAction(FETCH_OPTION_SERVICE_CHILD_SUCCESS)
export const fetchOptionServiceChildError = createAction(FETCH_OPTION_SERVICE_CHILD_ERROR)

const SET_SERVICE_CHILD = 'SET_SERVICE_CHILD'
export const setServiceChild = createAction(SET_SERVICE_CHILD)

const CLEAR_SERVICE_CHILD = 'CLEAR_SERVICE_CHILD'
export const clearServiceChild =  createAction(CLEAR_SERVICE_CHILD)

const SET_MODAL_DETAIL = 'SET_MODAL_DETAIL'
export const setModalDetail = createAction(SET_MODAL_DETAIL)
