import {createAction} from 'redux-actions'

export const STATISTIC_BY_TOTAL= 'STATISTIC_BY_TOTAL'
const STATISTIC_BY_TOTAL_REQUEST = 'STATISTIC_BY_TOTAL_REQUEST'
const STATISTIC_BY_TOTAL_SUCCESS = 'STATISTIC_BY_TOTAL_SUCCESS'
const STATISTIC_BY_TOTAL_ERROR = 'STATISTIC_BY_TOTAL_ERROR'

export const STATISTIC_BY_COMPARE = 'STATISTIC_BY_COMPARE'
const STATISTIC_BY_COMPARE_REQUEST = 'STATISTIC_BY_COMPARE_REQUEST'
const STATISTIC_BY_COMPARE_SUCCESS = 'STATISTIC_BY_COMPARE_SUCCESS'
const STATISTIC_BY_COMPARE_ERROR = 'STATISTIC_BY_COMPARE_ERROR'

export const STATISTIC_BY_EMPLOYEE = 'STATISTIC_BY_EMPLOYEE'
const STATISTIC_BY_EMPLOYEE_REQUEST = 'STATISTIC_BY_EMPLOYEE_REQUEST'
const STATISTIC_BY_EMPLOYEE_SUCCESS = 'STATISTIC_BY_EMPLOYEE_SUCCESS'
const STATISTIC_BY_EMPLOYEE_ERROR = 'STATISTIC_BY_EMPLOYEE_ERROR'

export const STATISTIC_BY_SERVICE = 'STATISTIC_BY_SERVICE'
const STATISTIC_BY_SERVICE_REQUEST = 'STATISTIC_BY_SERVICE_REQUEST'
const STATISTIC_BY_SERVICE_SUCCESS = 'STATISTIC_BY_SERVICE_SUCCESS'
const STATISTIC_BY_SERVICE_ERROR = 'STATISTIC_BY_SERVICE_ERROR'

export const STATISTIC_BY_TOTAL_OF_EMPLOYEE = 'STATISTIC_BY_TOTAL_OF_EMPLOYEE'
const STATISTIC_BY_TOTAL_OF_EMPLOYEE_REQUEST = 'STATISTIC_BY_TOTAL_OF_EMPLOYEE_REQUEST'
const STATISTIC_BY_TOTAL_OF_EMPLOYEE_SUCCESS = 'STATISTIC_BY_TOTAL_OF_EMPLOYEE_SUCCESS'
const STATISTIC_BY_TOTAL_OF_EMPLOYEE_ERROR = 'STATISTIC_BY_TOTAL_OF_EMPLOYEE_ERROR'

export const STATISTIC_BY_SERVICE_OF_EMPLOYEE = 'STATISTIC_BY_SERVICE_OF_EMPLOYEE'
const STATISTIC_BY_SERVICE_OF_EMPLOYEE_REQUEST = 'STATISTIC_BY_SERVICE_OF_EMPLOYEE_REQUEST'
const STATISTIC_BY_SERVICE_OF_EMPLOYEE_SUCCESS = 'STATISTIC_BY_SERVICE_OF_EMPLOYEE_SUCCESS'
const STATISTIC_BY_SERVICE_OF_EMPLOYEE_ERROR = 'STATISTIC_BY_SERVICE_OF_EMPLOYEE_ERROR'

export const statiticByTotalRequest = createAction(STATISTIC_BY_TOTAL_REQUEST)
export const statiticByTotalSuccess = createAction(STATISTIC_BY_TOTAL_SUCCESS)
export const statiticByTotalError = createAction(STATISTIC_BY_TOTAL_ERROR)

export const statiticByCompareRequest = createAction(STATISTIC_BY_COMPARE_REQUEST)
export const statiticByCompareSuccess = createAction(STATISTIC_BY_COMPARE_SUCCESS)
export const statiticByCompareError = createAction(STATISTIC_BY_COMPARE_ERROR)

export const statiticByEmployeeRequest = createAction(STATISTIC_BY_EMPLOYEE_REQUEST)
export const statiticByEmployeeSuccess = createAction(STATISTIC_BY_EMPLOYEE_SUCCESS)
export const statiticByEmployeeError = createAction(STATISTIC_BY_EMPLOYEE_ERROR)

export const statiticByServiceRequest = createAction(STATISTIC_BY_SERVICE_REQUEST)
export const statiticByServiceSuccess = createAction(STATISTIC_BY_SERVICE_SUCCESS)
export const statiticByServiceError = createAction(STATISTIC_BY_SERVICE_ERROR)

export const statiticByTotalOfEmployeeRequest = createAction(STATISTIC_BY_TOTAL_OF_EMPLOYEE_REQUEST)
export const statiticByTotalOfEmployeeSuccess = createAction(STATISTIC_BY_TOTAL_OF_EMPLOYEE_SUCCESS)
export const statiticByTotalOfEmployeeError = createAction(STATISTIC_BY_TOTAL_OF_EMPLOYEE_ERROR)

export const statiticByServiceOfEmployeeRequest = createAction(STATISTIC_BY_SERVICE_OF_EMPLOYEE_REQUEST)
export const statiticByServiceOfEmployeeSuccess = createAction(STATISTIC_BY_SERVICE_OF_EMPLOYEE_SUCCESS)
export const statiticByServiceOfEmployeeError = createAction(STATISTIC_BY_SERVICE_OF_EMPLOYEE_ERROR)
